
import { icons } from "lucide-react";
import "./globals.css";



export const metadata = {
  title: "home page",
  description: "Generated by create next app",
  icons:{
icon:"public/globe.svg"

  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
     
      >
        {children}
      </body>
    </html>
  );
}
